name             'chef-mysql_datalake'
maintainer       'greg lane'
maintainer_email 'glane@gannett.com'
license          'All rights reserved'
description      'Installs/Configures chef-mysql_datalake'
long_description 'Installs/Configures chef-mysql_datalake'
version          '0.1.0'

depends 'mysql'
depends 'lvm'
depends 'selinux'
depends 'sysctl'
depends 'limits'
depends 'database'
depends 'mysql2_chef_gem'
depends 'cron'